Comercial/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("create/", views.CrearOrden.as_view(), name="orden_create"),
    path(
        "create/pdf_orden/",
        views.PdfView.as_view(),
        {"plantilla": "Comercial/pdf_orden.html"},
        name="pdf_orden",
    ),
    path(
        "create/pdf_garantía/",
        views.PdfView.as_view(),
        {"plantilla": "Comercial/pdf_garantia.html"},
        name="pdf_garantia",
    ),
    path(
        "create/imp_orden/",
        views.PDFOrden.as_view(),
        {"plantilla": "orden/orden_nueva.html"},
        name="imp_orden",
    ),
    path(
        "create/imp_garantia/",
        views.PDFOrden.as_view(),
        {"plantilla": "orden/carta.html"},
        name="imp_garantia",
    ),
    path("create/gestion_orden/", views.PDFGestion.as_view(), name="gestion_orden"),
  
    re_path(
        r"^ordenprimaria/(?P<pk>[0-9]+)/$",
        views.UpdateOrder.as_view(),
        name="update_order",
    ),
    re_path(
        r"^ordenprimaria/(?P<pk>[0-9]+)/delete/$",
        views.DeleteOrder.as_view(),
        name="delete_order",
    ),
   
    re_path(
        r"^index/gestion_telefono/(?P<pk>\d+)/$",
        views.OrdenLlamada.as_view(),
        name="gestion_telefono_llamar",
    ),
    re_path(
        r"^create/pdf_orden/(?P<ordenprimaria_id>\d+)/$",
        views.reimprimir_orden,
        {"plantilla": "Comercial/pdf_orden.html"},
        name="reimprimir_orden",
    ),
    re_path(r"^cerrar/(?P<pk>\d+)/$", views.CerrarOrden.as_view(), name="orden_close"),
]

SIGEST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('taller/', include('Taller.urls')),
    path('comercial/', include('Comercial.urls')),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


base/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import authentication


urlpatterns = [
    path("", authentication.loggin, name="loggin"),
    path("logout/", authentication.loggedout, name="logout"),
    re_path(r"^accounts/login/$", authentication.user_login, name="login"),
]

Comercial/models.py
from django.db import models

# Create your models here.

from base.models import (
    Centro,
    Trabajador,
    Prefijo,
    Modelo,
    Tecnologia,
    Defecto,
    Estado,
    ManoObra,
    Consumo_Recursos,
)

class OrdenPrimaria(models.Model):
    """Datos iniciales de la Orden"""

    No_orden = models.CharField(max_length=50)
    fecha_creacion = models.DateTimeField()
    fecha_entrada_taller = models.DateTimeField(blank=True, null=True)
    centro = models.ForeignKey(Centro, on_delete=models.CASCADE)
    ordena = models.ForeignKey(
        Trabajador, on_delete=models.CASCADE, related_name="ordena"
    )
    """ Estos son campos nuevos"""
    folio_venta = models.CharField(max_length=80, blank=True, null=True)
    fecha_venta = models.DateTimeField(blank=True, null=True)
    # equipo=models.ForeignKey(Equipo, on_delete=models.CASCADE, blank=True, null=True)
    garantia = models.CharField(max_length=20, blank=True, null=True)
    fecha_vencimiento_garantia = models.DateTimeField(null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    """ Aquí termina"""
    prefijo = models.ForeignKey(Prefijo, on_delete=models.CASCADE)
    servicio = models.CharField(max_length=20)
    modelo = models.ForeignKey(Modelo, on_delete=models.CASCADE)
    tecnologia = models.ForeignKey(Tecnologia, on_delete=models.CASCADE)
    defecto = models.ManyToManyField(Defecto)
    serie = models.CharField(max_length=80)
    nombre_cliente_entrega = models.CharField(max_length=120)
    direccion_cliente_entrega = models.CharField(max_length=120)
    ci_cliente_entrega = models.CharField(max_length=20)
    contacto_telefono = models.CharField(max_length=20)
    propietario = models.BooleanField(default=False)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    confComercial = models.BooleanField(default=False)
    confTaller = models.BooleanField(default=False)
    entrega = models.ForeignKey(
        Trabajador,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="entrega",
    )

    """ Datos a llenar al reparar"""
    fecha_defectacion = models.DateTimeField(blank=True, null=True)
    repara = models.ForeignKey(
        Trabajador,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="repara",
    )
    accion_reparacion = models.TextField(null=True, blank=True)
    mano_obra = models.ForeignKey(
        ManoObra, on_delete=models.CASCADE, blank=True, null=True
    )
    consumo_recursos = models.ManyToManyField(Consumo_Recursos, blank=True)

    """ Datos antes de cerrada la orden para la gestion de las salidas"""
    fecha_gestion = models.DateTimeField(blank=True, null=True)
    llama = models.ForeignKey(
        Trabajador,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="llama",
    )
    nombre_cliente = models.CharField(max_length=160, blank=True, null=True)
    impresion = models.BooleanField(default=False)

    """ Datos a llenar para cerrar la orden"""
    fecha_cierre = models.DateTimeField(null=True, blank=True)
    cierra = models.ForeignKey(
        Trabajador,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="cierra",
    )
    nombre_cliente_recibe = models.CharField(max_length=120, blank=True, null=True)
    direccion_cliente_recibe = models.CharField(max_length=120, blank=True, null=True)
    ci_cliente_recibe = models.CharField(max_length=20, blank=True, null=True)
    cerrada = models.BooleanField(default=False)

    """ Este dato es muy importante y se actualiza tanto cuando se gestionan los telefonos como cuando cierra"""
    garantia_reparacion = models.DateTimeField(blank=True, null=True)
    """Variable para poder hacer analisis de tiempos"""
    tiempo = models.IntegerField(blank=True, null=True)

    objects = models.Manager()

    def __str__(self):
        return self.No_orden

    # def __str__(self):
    #   return self.No_orden

    class Meta:
        verbose_name_plural = "Ordenes"


class ReporteGestionImpreso(models.Model):
    reporta = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    ordenes = models.ManyToManyField(OrdenPrimaria)

Comercial/views.py
# import os
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import View, TemplateView
from django.template.loader import render_to_string
import datetime
from django.utils import timezone


from .forms import (
    PrimaryOrderForm,
    TalkForm,
    CloseOrderForm,
)
from base.models import (
    Modelo,
    Defecto,
    Estado,
    Recursos,
    Tecnologia,
    Prefijo,
    ManoObra,
    Consumo_Recursos,
)
from Taller.models import OrdenHistorico 
from .models import OrdenPrimaria, ReporteGestionImpreso
from base.views import BaseDatosMixin, CalcularTiempo
from Taller.files_views import render_to_pdf

# from django.views.decorators.csrf import csrf_protect
# import json
# from io import StringIO
# from django.template.loader import get_template
# from xhtml2pdf import pisa
# import cgi




class PdfView(BaseDatosMixin, TemplateView):
    def get(self, request, plantilla, *args, **kwargs):
        # pdf=render_to_pdf("orden/orden_trabajo.html")
        modelo = OrdenPrimaria.objects.filter(ordena=request.user.trabajador)
        for modelo in modelo:
            orden_id = modelo.id
        model = get_object_or_404(OrdenPrimaria, id=orden_id)
        context = super().get_context_data(**kwargs)
        context["model"] = model
        return render(request, plantilla, context)


@login_required
def pdf_view(request, plantilla):
    Orden = OrdenPrimaria.objects.filter(centro=request.user.trabajador.centro).filter(
        cerrada=False
    )
    modelComercial = Orden.filter(confComercial=False)
    cantidad = modelComercial.count()
    modelTaller = Orden.filter(confComercial=True).filter(confTaller=False)
    cantidad1 = modelTaller.count()
    modelo = OrdenPrimaria.objects.filter(ordena=request.user.trabajador)
    for model in modelo:
        orden_id = model.id
        model = get_object_or_404(OrdenPrimaria, id=orden_id)
    return render(
        request,
        plantilla,
        {
            "cantidad": cantidad,
            "modelComercial": modelComercial,
            "cantidad1": cantidad1,
            "modelTaller": modelTaller,
            "model": model,
        },
    )


class PDFOrden(View):
    """
    Regresa PDF basando en template Django/HTML
    """

    def get(self, request, plantilla, *args, **kwargs):
        # pdf=render_to_pdf("orden/orden_trabajo.html")
        modelo = OrdenPrimaria.objects.filter(ordena=request.user.trabajador)
        for model in modelo:
            orden_id = model.id
        model = get_object_or_404(OrdenPrimaria, id=orden_id)
        pdf = render_to_pdf(plantilla, {"model": model})
        return HttpResponse(pdf, content_type="application/pdf")


class PDFGestion(LoginRequiredMixin, View):
    """
    Regresa PDF basando en template Django/HTML
    """

    def get(self, request, *args, **kwargs):
        # pdf=render_to_pdf("orden/orden_trabajo.html")
        user = request.user
        model = (
            OrdenPrimaria.objects.filter(centro=user.trabajador.centro)
            .exclude(cerrada=True)
            .exclude(nombre_cliente=None)
            .filter(impresion=False)
            .filter(llama=user.trabajador)
        )
        reporte_gestion = ReporteGestionImpreso.objects.create(reporta=user.trabajador)
        for modelo in model:
            reporte_gestion.ordenes.add(modelo)
            modelo.impresion = True
            modelo.save()
        reporte_gestion.save()
        pdf = render_to_pdf("orden/gest_reparada.html", {"model": model, "user": user})
        return HttpResponse(pdf, content_type="application/pdf")


def reimprimir_orden(request, plantilla, ordenprimaria_id):
    Orden = OrdenPrimaria.objects.filter(centro=request.user.trabajador.centro)
    modelComercial = Orden.filter(confComercial=False)
    cantidad = modelComercial.count()
    modelTaller = Orden.filter(confComercial=True).filter(confTaller=False)
    cantidad1 = modelTaller.count()
    for model in Orden:
        model = get_object_or_404(Orden, id=ordenprimaria_id)
    return render(
        request,
        plantilla,
        {
            "cantidad": cantidad,
            "modelComercial": modelComercial,
            "cantidad1": cantidad1,
            "modelTaller": modelTaller,
            "model": model,
        },
    )


class CrearOrden(BaseDatosMixin, PermissionRequiredMixin, CreateView):
    model = OrdenPrimaria
    form_class = PrimaryOrderForm
    template_name = "Comercial/ordenprimaria_form.html"
    success_url = reverse_lazy("pdf_orden")
    permission_required = "Taller.add_ordenprimaria"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["defec"] = Defecto.objects.all()
        context["mod"] = Modelo.objects.all()
        context["prefijo"] = Prefijo.objects.all()
        return context

    """def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            messages.add_message(
                request, messages.INFO, "La orden fue creada con éxito"
            )
        return super(CrearOrden, self).dispatch(request, *args, **kwargs)"""

    def form_valid(self, form):
        d = datetime.datetime.now()
        last_d = d.year
        last_m = d.month
        user = self.request.user
        centro = user.trabajador.centro
        estado = get_object_or_404(Estado, pk=1)
        self.object = form.save(commit=False)
        temp = 1
        ordenp = OrdenPrimaria.objects.all()
        ordenp.order_by("No_orden")
        for orden in ordenp:
            fe = orden.fecha_creacion
            if fe.year == last_d and fe.month == last_m:
                temp += 1
            else:
                temp = 1

        self.object.No_orden = "%s%s%s" % (str(last_d), str(last_m), str(temp))
        self.object.centro = centro
        self.object.ordena = user.trabajador
        self.object.fecha_creacion = datetime.datetime.now()
        self.object.estado = estado
        self.object.tecnologia = self.object.modelo.tecnologia
        # self.object.codigo_sap=self.object.modelo.codigo_sap
        # self.object.descripcion=self.object.modelo.descripcion
        self.object = form.save()

        # modelact=get_object_or_404(OrdenPrimaria, pk=self.object.pk)
        return super(CrearOrden, self).form_valid(form)



class UpdateOrder(BaseDatosMixin, PermissionRequiredMixin, UpdateView):
    model = OrdenPrimaria
    template_name = "Comercial/ordenprimaria_form.html"
    success_url = reverse_lazy("list_updates")
    permission_required = "Taller.add_ordenprimaria"
    form_class = PrimaryOrderForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["defec"] = Defecto.objects.all()
        context["mod"] = Modelo.objects.all()
        context["prefijo"] = Prefijo.objects.all()
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            messages.add_message(
                request, messages.INFO, "La orden fue actualizada con éxito"
            )
        return super(UpdateOrder, self).dispatch(request, *args, **kwargs)


class DeleteOrder(BaseDatosMixin, PermissionRequiredMixin, DeleteView):
    model = OrdenPrimaria
    template_name = "Comercial/delete_order.html"
    success_url = reverse_lazy("list_updates")
    permission_required = "Taller.add_ordenprimaria"


class CerrarOrden(BaseDatosMixin, PermissionRequiredMixin, UpdateView):
    model = OrdenPrimaria
    success_url = reverse_lazy("ordenes_reparadas")
    template_name = "Comercial/ordencerrada_form.html"
    permission_required = "Taller.add_ordenprimaria"
    form_class = CloseOrderForm

    @method_decorator(login_required)
    def dispatch(self, request, pk, *args, **kwargs):
        if request.method == "POST":
            messages.add_message(
                request, messages.INFO, "La orden se ha cerrado con éxito"
            )
        return super(CerrarOrden, self).dispatch(request, pk, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        if self.object.fecha_gestion == None:
            self.object.fecha_gestion = datetime.datetime.now()
        self.object = form.save(commit=False)
        self.object.cerrada = True
        now = timezone.now()
        now = datetime.datetime.strftime(now, "%d/%m/%Y")
        now = datetime.datetime.strptime(now, "%d/%m/%Y")
        fechastr = datetime.datetime.strftime(self.object.fecha_gestion, "%d/%m/%Y")
        fechaCalulo = datetime.datetime.strptime(fechastr, "%d/%m/%Y")
        fecha = (now - fechaCalulo) / datetime.timedelta(days=1)
        if fecha < 15:
            self.object.garantia_reparacion = now + datetime.timedelta(days=30)
        else:
            self.object.garantia_reparacion = fecha_gestion + datetime.timedelta(
                days=45
            )

        self.object.cierra = user.trabajador
        self.object.fecha_cierre = datetime.datetime.now()
        self.object = form.save()
        return super(CerrarOrden, self).form_valid(form)


class OrdenLlamada(BaseDatosMixin, PermissionRequiredMixin, UpdateView):
    model = OrdenPrimaria
    success_url = reverse_lazy("gestion_telefono")
    template_name = "Comercial/ordenllamada_form.html"
    permission_required = "Taller.add_ordenprimaria"
    form_class = TalkForm

    @method_decorator(login_required)
    def dispatch(self, request, pk, *args, **kwargs):

Comercial/templates/Comercial/delete_order.html
{% extends "base.html" %}
{% load static%}
{% block content %}
<!-- page content -->
<form class="form-horizontal form-label-left" action="" name="informacion" method="post">
    {%csrf_token%}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Orden a eliminar</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-4 col-sm-6 col-xs-12"></div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="pricing">
                            <div class="title">
                                <h1>Orden: {{object.No_orden}}</h1>
                                <h2></h2>
                            </div>
                            <div class="x_content">
                                <div class="">
                                    <div class="pricing_features">
                                        <ul class="list-unstyled text-left">
                                            <li><i class="fa fa-check text-success"></i> <strong>Servicio: </strong>{{object.servicio}}</li>
                                            <li><i class="fa fa-check text-success"></i> <strong>Modelo: </strong>{{object.modelo.nombre}}</li>
                                            <li><i class="fa fa-check text-success"></i><strong> Tecnología: </strong>{{object.modelo.tecnologia.nombre}}</li>
                                            <li><i class="fa fa-check text-success"></i> <strong>Serie: </strong>{{object.serie}}</li>
                                            <li><i class="fa fa-check text-success"></i><strong>Ordena: </strong>{{object.ordena}}</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="pricing_footer">
                                    <button type="submit" class="btn btn-success btn-block">Delete Orden <span> now!</span></button>
                                    <p>
                                        <button type="submit" class="btn btn-block"><a href="{% url 'list_updates' %}">Cancelar eliminación</a></button>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- /page content -->
{% endblock %}
{%block jscontent%}
<script src="{% static 'js/csrftoken.js' %}"></script>
{%endblock%}

Comercial/templates/Comercial/ordenprimaria_form.html
{% extends "base.html" %}
{% load static %}
{%block stylecontent%}
<link href="{% static 'css/vendors/google-code-prettify/bin/prettify.min.css' %}" rel="stylesheet">
<!-- Select2 -->
<link href="{% static 'css/vendors/select2/dist/css/select2.min.css' %}" rel="stylesheet">
<!-- Switchery -->
<link href="{% static 'css/vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
<!-- iCheck -->
<link href="{% static 'css/vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
<!-- starrr -->
<link href="{% static 'css/vendors/starrr/dist/starrr.css' %}" rel="stylesheet">
<!-- bootstrap-daterangepicker -->
<link href="{% static 'css/vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
<!-- bootstrap-datetimepicker -->
<link href="{% static 'css/vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylesnew.css' %}" />
{%endblock%}
{% block content %}
<form class="form-horizontal form-label-left" action="." name="informacion" method="post">
    {%csrf_token%}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel pagenew-div">
                <div class="x_title">
                    <h2>Datos Orden <small>de servicio</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    
                    <!-- Smart Wizard -->
                    <div class="form-group" style="margin:0px">
                        <div class="col-md-2">
                            {%if form.prefijo.errors%}
                            {%for error in form.prefijo.errors%}
                             <p style="color:red">{{error}}</p>
                             {%endfor%}
                             {%endif%}
                        </div>
                        <div class="col-md-4">
                            {%if form.servicio.errors%}
                            {%for error in form.servicio.errors%}
                             <p style="color:red"><strong>{{error}}</strong></p>
                             {%endfor%}
                             {%endif%}
                        </div>
                        <div class="col-md-2">
                        </div>
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-1">
                        </div>
                    </div>
                    <div class="form-group" style="margin:0px">
                        <div class="col-sm-2">
                            <div class="form-group" style="text-align:center">
                            <label>Prefijo <span class="required"></span>
                            </label>
                            {{form.prefijo}}
                        </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group" style="text-align:center">
                            <label>Servicio <span class="required"></span>
                            </label>
                            
                             {{form.servicio}}
                          </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group" style="text-align:center">
                            <label>Modelo <span class="required"></span>
                            </label>
                            {{form.modelo}}
                        </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group" style="text-align:center">
                            <label>Serie <span class="required"></span>
                            </label>
                            {{form.serie}}
                        </div>
                        </div>
                        <div class="col-sm-2" >
                            <div class="form-group" style="text-align:center">
                            <label>Garantía
                            </label>
                            <select class="select2_single form-control forms-input" name="garantia" id="id_garantia" required="required" value="{{object.garantia}}">
                                <option value="{{object.pk}}" selected>{{object.garantia}}</option>
                                <option>SI</option>
                                <option>NO</option>
                            </select>
                        </div>
                        </div>
                    </div>

                    <div class="form-group" style="margin:0px">
                    <div class="col-sm-3">
                        <div class="form-group" style="text-align:center">
                            <label>Venc. Garantía <span class="required"></span>
                            </label>
                            <div class='input-group date' id='myDatepicker'>
                                {{form.fecha_vencimiento_garantia}}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group" style="text-align:center">
                            <label>Folio <span class="required"></span>
                            </label>
                            {{form.folio_venta}}
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group" style="text-align:center">
                            <label>Fecha Venta <span class="required"></span>
                            </label>
                            <div class='input-group date' id='myDatepicker2'>
                                {{form.fecha_venta}}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group" style="text-align:center">
                            <label >Defectos<span class="required"></span>
                            </label>
                            {{form.defecto}}
                        </div>
                    </div>
                </div>
                <div class="form-group" style="margin:0px">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Observaciones</label>
                            {{form.observaciones}}
                        </div>
                    </div>
                </div>
                <div class="form-group" style="margin:0px">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Nombre del cliente <span class="required"></span>
                            </label>
                            {{form.nombre_cliente_entrega}}
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Dirección Particular <span class="required"></span>
                            </label>
                            {{form.direccion_cliente_entrega}}
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>CI del cliente<span class="required"></span>
                            </label>
                            {{form.ci_cliente_entrega}}
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Contacto Telefónico<span class="required"></span>
                            </label>
                            {{form.contacto_telefono}}
                        </div>
                    </div>
                </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    {{form.propietario}}
                                    <strong>Propietario</strong>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-11"></div>
                        <div class="col-sm-1">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{%endblock%}
{%block jscontent%}
<script src="{% static 'js/csrftoken.js' %}"></script>
<script src="{% static 'css/vendors/validator/validator.js' %}"></script>
<!-- bootstrap-daterangepicker -->
<script src="{% static 'css/vendors/moment/min/moment.min.js' %}"></script>
<script src="{% static 'css/vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- bootstrap-datetimepicker -->
<script src="{% static 'css/vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'css/vendors/select2/dist/js/select2.full.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'css/vendors/iCheck/icheck.min.js' %}"></script>
<script src="{% static 'css/vendors/moment/min/moment.min.js' %}"></script>
<script>
$("#myDatepicker").datetimepicker({
    format: 'DD/MM/YYYY hh:mm:ss'
});

$("#myDatepicker2").datetimepicker({
    format: 'DD/MM/YYYY hh:mm:ss'
});
</script>
{%endblock%}